Repository BeelanMX/scrapCFEBot, pull requests merged in 2021-09, with the labels that each got.

#21 Adding commands
  bot/index.js
Labels: nodeJs, discordBot

#29 Compare the time of the file and today's date
  index.js
  scrapperFunctions/index.js
  webScraping/cfeScrapper.js
  webScraping/readme.md
Labels: documentation, webScraping

#31 Change the files arquitecture
  bot/commands/cfe.js
  bot/env.sample
  bot/index.js
  commands/cfe.js
  env.sample
  index.js
  package-lock.json
  package.json
  yarn.lock
Labels: nodeJs, discordBot

#35 Fix of validation
  index.js
  utils/Files.js
  utils/validator.js
  webScraping/cfeScrapper.js
Labels: help wanted

#36 Make documentation and fix minor code issues
  README.md
  commands/cfe.js
  commands/help.js
  index.js
Labels: discordBot

#33 Separate mainFunction to a file in utils/
  commands/cfe.js
  env.sample
  index.js
  utils/Files.js
  utils/validator.js
  webScraping/cfeScrapper.js
Labels: nodeJs, webScraping

#41 Validate that the array's args isn't empty
  commands/cfe.js
Labels: bug

#42 Close browser if the search doesn't have results
  scrapperFunctions/index.js
  webScraping/cfeScrapper.js
Labels: nodeJs, webScraping

#48 Dev ram/message parcer
  commands/cfe.js
  utils/files.js
  utils/sendTableMessage.js
  yarn.lock
Labels: nodeJs, discordBot

#49 Dev ram/json to message
  commands/cfe.js
  commands/help.js
Labels: nodeJs, discordBot
