Repository BeelanMX/scrapCFEBot, pull requests merged in 2021-08, with the labels that each got.

#12 Do a search
  cfeScraping/index.js
  index.js
Labels: enhancement

#15 Change the format of the file with the data from table
  .gitignore
  assets/.gitkeep
  cfeScraping/index.js
  index.js
  package.json
Labels: nodeJs, webScraping

#19 Discord Bot greeting
  README.md
  bot/env.sample
  bot/index.js
Labels: nodeJs, discordBot

#23 Add a progress bar
  cfeScraping/index.js
  index.js
Labels: nodeJs, webScraping
