Repository BeelanMX/scrapCFEBot, pull requests merged in 2021-10, with the labels that each got.

#45 Send a message with the data obtained
  commands/cfe.js
  commands/help.js
  package-lock.json
  package.json
  scrapperFunctions/index.js
  utils/sendTableMessage.js
  webScraping/cfeScrapper.js
  yarn.lock
Labels: discordBot

#55 Dev ram/issue#54
  Procfile
  package-lock.json
  webScraping/cfeScrapper.js
Labels: nodeJs, discordBot, deploy

#68 Add strict comparison
  commands/cfe.js
  scrapperFunctions/index.js
  webScraping/cfeScrapper.js
Labels: nodeJs

#54 Add CFE BOT
  .gitignore
  CFEScraping/index.js
  Procfile
  README.md
  assets/.gitkeep
  commands/cfe.js
  commands/help.js
  env.sample
  index.js
  package-lock.json
  package.json
  scrapperFunctions/index.js
  scrapperFunctions/readme.md
  utils/files.js
  utils/sendTableMessage.js
  utils/validator.js
  webScraping/cfeScrapper.js
  webScraping/readme.md
  yarn.lock
Labels: nodeJs, webScraping, discordBot

#69 Remove detalle & testigoSocial from data
  webScraping/cfeScrapper.js
Labels: nodeJs, webScraping

#67 Compare the data sended with the data obtained
  commands/cfe.js
  commands/help.js
Labels: nodeJs, discordBot

#70 Separe functions
  scrapperFunctions/index.js
  utils/getRows.js
  utils/tableToArray.js
Labels: nodeJs, webScraping
